package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the newsletter table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="newsletter"
 */
public abstract class BaseNewsletter  implements Serializable {

	public static String PROP_ID_NEWS = "IdNews";
	public static String PROP_CONTENU_NEWS = "ContenuNews";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idNews;

	// fields
	private java.lang.String _contenuNews;

	// collections
	private java.util.Set _recevoirSet;


	// constructors
	public BaseNewsletter () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseNewsletter (java.lang.Long _idNews) {
		this.setIdNews(_idNews);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseNewsletter (
		java.lang.Long _idNews,
		java.lang.String _contenuNews) {

		this.setIdNews(_idNews);
		this.setContenuNews(_contenuNews);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_NEWS"
     */
	public java.lang.Long getIdNews () {
		return _idNews;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idNews the new ID
	 */
	public void setIdNews (java.lang.Long _idNews) {
		this._idNews = _idNews;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: CONTENU_NEWS
	 */
	public java.lang.String getContenuNews () {
		return _contenuNews;
	}

	/**
	 * Set the value related to the column: CONTENU_NEWS
	 * @param _contenuNews the CONTENU_NEWS value
	 */
	public void setContenuNews (java.lang.String _contenuNews) {
		this._contenuNews = _contenuNews;
	}


	/**
	 * Return the value associated with the column: RecevoirSet
	 */
	public java.util.Set getRecevoirSet () {
		return this._recevoirSet;
	}

	/**
	 * Set the value related to the column: RecevoirSet
	 * @param _recevoirSet the RecevoirSet value
	 */
	public void setRecevoirSet (java.util.Set _recevoirSet) {
		this._recevoirSet = _recevoirSet;
	}
	
	public void addToRecevoirSet (Object obj) {
		if (null == this._recevoirSet) this._recevoirSet = new java.util.HashSet();
		this._recevoirSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseNewsletter)) return false;
		else {
			model.base.BaseNewsletter mObj = (model.base.BaseNewsletter) obj;
			if (null == this.getIdNews() || null == mObj.getIdNews()) return false;
			else return (this.getIdNews().equals(mObj.getIdNews()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdNews()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdNews().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}