package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public class BaseRecevoirPK implements Serializable {

	private int hashCode = Integer.MIN_VALUE;

	private hibernate.Utilisateur _login;
	private hibernate.Newsletter _idNews;

	public BaseRecevoirPK () {}
	
	public BaseRecevoirPK (
		hibernate.Utilisateur _login,
		hibernate.Newsletter _idNews) {

		this.setLogin(_login);
		this.setIdNews(_idNews);
	}


	public hibernate.Utilisateur getLogin () {
		return _login;
	}

	public void setLogin (hibernate.Utilisateur _login) {
		hashCode = Integer.MIN_VALUE;
		this._login = _login;
	}

	public hibernate.Newsletter getIdNews () {
		return _idNews;
	}

	public void setIdNews (hibernate.Newsletter _idNews) {
		hashCode = Integer.MIN_VALUE;
		this._idNews = _idNews;
	}

	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.RecevoirPK)) return false;
		else {
			hibernate.RecevoirPK mObj = (hibernate.RecevoirPK) obj;
			if (null != this.getLogin() && null != mObj.getLogin()) {
				if (!this.getLogin().equals(mObj.getLogin())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getIdNews() && null != mObj.getIdNews()) {
				if (!this.getIdNews().equals(mObj.getIdNews())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}

	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getLogin()) {
				sb.append(this.getLogin().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getIdNews()) {
				sb.append(this.getIdNews().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}

}