package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public class BaseUtilisateurPK implements Serializable {

	private int hashCode = Integer.MIN_VALUE;

	private java.lang.String _login;
	private java.lang.String _email;

	public BaseUtilisateurPK () {}
	
	public BaseUtilisateurPK (
		java.lang.String _login,
		java.lang.String _email) {

		this.setLogin(_login);
		this.setEmail(_email);
	}


	public java.lang.String getLogin () {
		return _login;
	}

	public void setLogin (java.lang.String _login) {
		hashCode = Integer.MIN_VALUE;
		this._login = _login;
	}

	public java.lang.String getEmail () {
		return _email;
	}

	public void setEmail (java.lang.String _email) {
		hashCode = Integer.MIN_VALUE;
		this._email = _email;
	}

	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.UtilisateurPK)) return false;
		else {
			hibernate.UtilisateurPK mObj = (hibernate.UtilisateurPK) obj;
			if (null != this.getLogin() && null != mObj.getLogin()) {
				if (!this.getLogin().equals(mObj.getLogin())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getEmail() && null != mObj.getEmail()) {
				if (!this.getEmail().equals(mObj.getEmail())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}

	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getLogin()) {
				sb.append(this.getLogin().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getEmail()) {
				sb.append(this.getEmail().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}

}