package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the jeu table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="jeu"
 */
public abstract class BaseJeu  implements Serializable {

	public static String PROP_TITRE_JEU = "TitreJeu";
	public static String PROP_CONTEXTE_JEU = "ContexteJeu";
	public static String PROP_REGLE_JEU = "RegleJeu";
	public static String PROP_LIEN_OFFICIEL = "LienOfficiel";
	public static String PROP_INFO_JEU = "InfoJeu";
	public static String PROP_ID_JEU = "IdJeu";
	public static String PROP_URL_JEU = "UrlJeu";
	public static String PROP_POINT_JEU = "PointJeu";
	public static String PROP_ID_TYPE_JEU = "IdTypeJeu";
	public static String PROP_MATERIEL_JEU = "MaterielJeu";
	public static String PROP_ADRESSE_IMAGE_JEU = "AdresseImageJeu";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idJeu;

	// fields
	private java.lang.String _adresseImageJeu;
	private java.lang.String _contexteJeu;
	private java.lang.String _infoJeu;
	private java.lang.String _regleJeu;
	private java.lang.String _lienOfficiel;
	private java.lang.String _urlJeu;
	private java.lang.String _pointJeu;
	private java.lang.String _titreJeu;
	private java.lang.String _materielJeu;

	// many to one
	private hibernate.TypeJeu _idTypeJeu;

	// collections
	private java.util.Set _moisSet;
	private java.util.Set _joueSet;


	// constructors
	public BaseJeu () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseJeu (java.lang.Long _idJeu) {
		this.setIdJeu(_idJeu);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseJeu (
		java.lang.Long _idJeu,
		hibernate.TypeJeu _idTypeJeu,
		java.lang.String _urlJeu,
		java.lang.String _titreJeu) {

		this.setIdJeu(_idJeu);
		this.setIdTypeJeu(_idTypeJeu);
		this.setUrlJeu(_urlJeu);
		this.setTitreJeu(_titreJeu);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_JEU"
     */
	public java.lang.Long getIdJeu () {
		return _idJeu;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idJeu the new ID
	 */
	public void setIdJeu (java.lang.Long _idJeu) {
		this._idJeu = _idJeu;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: ADRESSE_IMAGE_JEU
	 */
	public java.lang.String getAdresseImageJeu () {
		return _adresseImageJeu;
	}

	/**
	 * Set the value related to the column: ADRESSE_IMAGE_JEU
	 * @param _adresseImageJeu the ADRESSE_IMAGE_JEU value
	 */
	public void setAdresseImageJeu (java.lang.String _adresseImageJeu) {
		this._adresseImageJeu = _adresseImageJeu;
	}


	/**
	 * Return the value associated with the column: CONTEXTE_JEU
	 */
	public java.lang.String getContexteJeu () {
		return _contexteJeu;
	}

	/**
	 * Set the value related to the column: CONTEXTE_JEU
	 * @param _contexteJeu the CONTEXTE_JEU value
	 */
	public void setContexteJeu (java.lang.String _contexteJeu) {
		this._contexteJeu = _contexteJeu;
	}


	/**
	 * Return the value associated with the column: INFO_JEU
	 */
	public java.lang.String getInfoJeu () {
		return _infoJeu;
	}

	/**
	 * Set the value related to the column: INFO_JEU
	 * @param _infoJeu the INFO_JEU value
	 */
	public void setInfoJeu (java.lang.String _infoJeu) {
		this._infoJeu = _infoJeu;
	}


	/**
	 * Return the value associated with the column: REGLE_JEU
	 */
	public java.lang.String getRegleJeu () {
		return _regleJeu;
	}

	/**
	 * Set the value related to the column: REGLE_JEU
	 * @param _regleJeu the REGLE_JEU value
	 */
	public void setRegleJeu (java.lang.String _regleJeu) {
		this._regleJeu = _regleJeu;
	}


	/**
	 * Return the value associated with the column: LIEN_OFFICIEL
	 */
	public java.lang.String getLienOfficiel () {
		return _lienOfficiel;
	}

	/**
	 * Set the value related to the column: LIEN_OFFICIEL
	 * @param _lienOfficiel the LIEN_OFFICIEL value
	 */
	public void setLienOfficiel (java.lang.String _lienOfficiel) {
		this._lienOfficiel = _lienOfficiel;
	}


	/**
	 * Return the value associated with the column: URL_JEU
	 */
	public java.lang.String getUrlJeu () {
		return _urlJeu;
	}

	/**
	 * Set the value related to the column: URL_JEU
	 * @param _urlJeu the URL_JEU value
	 */
	public void setUrlJeu (java.lang.String _urlJeu) {
		this._urlJeu = _urlJeu;
	}


	/**
	 * Return the value associated with the column: POINT_JEU
	 */
	public java.lang.String getPointJeu () {
		return _pointJeu;
	}

	/**
	 * Set the value related to the column: POINT_JEU
	 * @param _pointJeu the POINT_JEU value
	 */
	public void setPointJeu (java.lang.String _pointJeu) {
		this._pointJeu = _pointJeu;
	}


	/**
	 * Return the value associated with the column: TITRE_JEU
	 */
	public java.lang.String getTitreJeu () {
		return _titreJeu;
	}

	/**
	 * Set the value related to the column: TITRE_JEU
	 * @param _titreJeu the TITRE_JEU value
	 */
	public void setTitreJeu (java.lang.String _titreJeu) {
		this._titreJeu = _titreJeu;
	}


	/**
	 * Return the value associated with the column: MATERIEL_JEU
	 */
	public java.lang.String getMaterielJeu () {
		return _materielJeu;
	}

	/**
	 * Set the value related to the column: MATERIEL_JEU
	 * @param _materielJeu the MATERIEL_JEU value
	 */
	public void setMaterielJeu (java.lang.String _materielJeu) {
		this._materielJeu = _materielJeu;
	}


	/**
     * @hibernate.property
     *  column=ID_TYPE_JEU
	 * not-null=true
	 */
	public hibernate.TypeJeu getIdTypeJeu () {
		return this._idTypeJeu;
	}

	/**
	 * Set the value related to the column: ID_TYPE_JEU
	 * @param _idTypeJeu the ID_TYPE_JEU value
	 */
	public void setIdTypeJeu (hibernate.TypeJeu _idTypeJeu) {
		this._idTypeJeu = _idTypeJeu;
	}


	/**
	 * Return the value associated with the column: MoisSet
	 */
	public java.util.Set getMoisSet () {
		return this._moisSet;
	}

	/**
	 * Set the value related to the column: MoisSet
	 * @param _moisSet the MoisSet value
	 */
	public void setMoisSet (java.util.Set _moisSet) {
		this._moisSet = _moisSet;
	}
	
	public void addToMoisSet (Object obj) {
		if (null == this._moisSet) this._moisSet = new java.util.HashSet();
		this._moisSet.add(obj);
	}



	/**
	 * Return the value associated with the column: JoueSet
	 */
	public java.util.Set getJoueSet () {
		return this._joueSet;
	}

	/**
	 * Set the value related to the column: JoueSet
	 * @param _joueSet the JoueSet value
	 */
	public void setJoueSet (java.util.Set _joueSet) {
		this._joueSet = _joueSet;
	}
	
	public void addToJoueSet (Object obj) {
		if (null == this._joueSet) this._joueSet = new java.util.HashSet();
		this._joueSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.base.BaseJeu)) return false;
		else {
			hibernate.base.BaseJeu mObj = (hibernate.base.BaseJeu) obj;
			if (null == this.getIdJeu() || null == mObj.getIdJeu()) return false;
			else return (this.getIdJeu().equals(mObj.getIdJeu()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdJeu()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdJeu().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}