package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the mois table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="mois"
 */
public abstract class BaseMois  implements Serializable {

	public static String PROP_ID_JEU = "IdJeu";
	public static String PROP_MOIS = "Mois";
	public static String PROP_CONSEIL_MOIS = "ConseilMois";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.util.Date _mois;

	// fields
	private java.lang.String _conseilMois;

	// many to one
	private hibernate.Jeu _idJeu;


	// constructors
	public BaseMois () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMois (java.util.Date _mois) {
		this.setMois(_mois);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseMois (
		java.util.Date _mois,
		hibernate.Jeu _idJeu) {

		this.setMois(_mois);
		this.setIdJeu(_idJeu);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="MOIS"
     */
	public java.util.Date getMois () {
		return _mois;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _mois the new ID
	 */
	public void setMois (java.util.Date _mois) {
		this._mois = _mois;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: CONSEIL_MOIS
	 */
	public java.lang.String getConseilMois () {
		return _conseilMois;
	}

	/**
	 * Set the value related to the column: CONSEIL_MOIS
	 * @param _conseilMois the CONSEIL_MOIS value
	 */
	public void setConseilMois (java.lang.String _conseilMois) {
		this._conseilMois = _conseilMois;
	}


	/**
     * @hibernate.property
     *  column=ID_JEU
	 * not-null=true
	 */
	public hibernate.Jeu getIdJeu () {
		return this._idJeu;
	}

	/**
	 * Set the value related to the column: ID_JEU
	 * @param _idJeu the ID_JEU value
	 */
	public void setIdJeu (hibernate.Jeu _idJeu) {
		this._idJeu = _idJeu;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.base.BaseMois)) return false;
		else {
			hibernate.base.BaseMois mObj = (hibernate.base.BaseMois) obj;
			if (null == this.getMois() || null == mObj.getMois()) return false;
			else return (this.getMois().equals(mObj.getMois()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getMois()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getMois().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}