package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the faq table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="faq"
 */
public abstract class BaseFaq  implements Serializable {

	public static String PROP_ID_FAQ = "IdFaq";
	public static String PROP_TITRE_FAQ = "TitreFaq";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idFaq;

	// fields
	private java.lang.String _titreFaq;

	// collections
	private java.util.Set _consulteSet;
	private java.util.Set _questionReponseSet;


	// constructors
	public BaseFaq () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseFaq (java.lang.Long _idFaq) {
		this.setIdFaq(_idFaq);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseFaq (
		java.lang.Long _idFaq,
		java.lang.String _titreFaq) {

		this.setIdFaq(_idFaq);
		this.setTitreFaq(_titreFaq);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_FAQ"
     */
	public java.lang.Long getIdFaq () {
		return _idFaq;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idFaq the new ID
	 */
	public void setIdFaq (java.lang.Long _idFaq) {
		this._idFaq = _idFaq;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: TITRE_FAQ
	 */
	public java.lang.String getTitreFaq () {
		return _titreFaq;
	}

	/**
	 * Set the value related to the column: TITRE_FAQ
	 * @param _titreFaq the TITRE_FAQ value
	 */
	public void setTitreFaq (java.lang.String _titreFaq) {
		this._titreFaq = _titreFaq;
	}


	/**
	 * Return the value associated with the column: ConsulteSet
	 */
	public java.util.Set getConsulteSet () {
		return this._consulteSet;
	}

	/**
	 * Set the value related to the column: ConsulteSet
	 * @param _consulteSet the ConsulteSet value
	 */
	public void setConsulteSet (java.util.Set _consulteSet) {
		this._consulteSet = _consulteSet;
	}
	
	public void addToConsulteSet (Object obj) {
		if (null == this._consulteSet) this._consulteSet = new java.util.HashSet();
		this._consulteSet.add(obj);
	}



	/**
	 * Return the value associated with the column: QuestionReponseSet
	 */
	public java.util.Set getQuestionReponseSet () {
		return this._questionReponseSet;
	}

	/**
	 * Set the value related to the column: QuestionReponseSet
	 * @param _questionReponseSet the QuestionReponseSet value
	 */
	public void setQuestionReponseSet (java.util.Set _questionReponseSet) {
		this._questionReponseSet = _questionReponseSet;
	}
	
	public void addToQuestionReponseSet (Object obj) {
		if (null == this._questionReponseSet) this._questionReponseSet = new java.util.HashSet();
		this._questionReponseSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseFaq)) return false;
		else {
			model.base.BaseFaq mObj = (model.base.BaseFaq) obj;
			if (null == this.getIdFaq() || null == mObj.getIdFaq()) return false;
			else return (this.getIdFaq().equals(mObj.getIdFaq()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdFaq()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdFaq().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}