package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the joue table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="joue"
 */
public abstract class BaseJoue  implements Serializable {

	public static String PROP_DUREE_JOUER = "DureeJouer";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private model.JouePK _id;

	// fields
	private java.util.Date _dureeJouer;


	// constructors
	public BaseJoue () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseJoue (model.JouePK _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseJoue (
		model.JouePK _id,
		java.util.Date _dureeJouer) {

		this.setId(_id);
		this.setDureeJouer(_dureeJouer);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public model.JouePK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (model.JouePK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: DUREE_JOUER
	 */
	public java.util.Date getDureeJouer () {
		return _dureeJouer;
	}

	/**
	 * Set the value related to the column: DUREE_JOUER
	 * @param _dureeJouer the DUREE_JOUER value
	 */
	public void setDureeJouer (java.util.Date _dureeJouer) {
		this._dureeJouer = _dureeJouer;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseJoue)) return false;
		else {
			model.base.BaseJoue mObj = (model.base.BaseJoue) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}