package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the recevoir table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="recevoir"
 */
public abstract class BaseRecevoir  implements Serializable {

	public static String PROP_ID = "Id";
	public static String PROP_DATE_RECEVOIR = "DateRecevoir";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private model.RecevoirPK _id;

	// fields
	private java.util.Date _dateRecevoir;


	// constructors
	public BaseRecevoir () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseRecevoir (model.RecevoirPK _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseRecevoir (
		model.RecevoirPK _id,
		java.util.Date _dateRecevoir) {

		this.setId(_id);
		this.setDateRecevoir(_dateRecevoir);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public model.RecevoirPK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (model.RecevoirPK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: DATE_RECEVOIR
	 */
	public java.util.Date getDateRecevoir () {
		return _dateRecevoir;
	}

	/**
	 * Set the value related to the column: DATE_RECEVOIR
	 * @param _dateRecevoir the DATE_RECEVOIR value
	 */
	public void setDateRecevoir (java.util.Date _dateRecevoir) {
		this._dateRecevoir = _dateRecevoir;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseRecevoir)) return false;
		else {
			model.base.BaseRecevoir mObj = (model.base.BaseRecevoir) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}