package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the question_reponse table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="question_reponse"
 */
public abstract class BaseQuestionReponse  implements Serializable {

	public static String PROP_ID_QUESTION_REPONSE = "IdQuestionReponse";
	public static String PROP_QUESTION = "Question";
	public static String PROP_REPONSE = "Reponse";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idQuestionReponse;

	// fields
	private java.lang.String _reponse;
	private java.lang.String _question;

	// collections
	private java.util.Set _faqSet;


	// constructors
	public BaseQuestionReponse () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseQuestionReponse (java.lang.Long _idQuestionReponse) {
		this.setIdQuestionReponse(_idQuestionReponse);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseQuestionReponse (
		java.lang.Long _idQuestionReponse,
		java.lang.String _reponse,
		java.lang.String _question) {

		this.setIdQuestionReponse(_idQuestionReponse);
		this.setReponse(_reponse);
		this.setQuestion(_question);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_QUESTION_REPONSE"
     */
	public java.lang.Long getIdQuestionReponse () {
		return _idQuestionReponse;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idQuestionReponse the new ID
	 */
	public void setIdQuestionReponse (java.lang.Long _idQuestionReponse) {
		this._idQuestionReponse = _idQuestionReponse;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: REPONSE
	 */
	public java.lang.String getReponse () {
		return _reponse;
	}

	/**
	 * Set the value related to the column: REPONSE
	 * @param _reponse the REPONSE value
	 */
	public void setReponse (java.lang.String _reponse) {
		this._reponse = _reponse;
	}


	/**
	 * Return the value associated with the column: QUESTION
	 */
	public java.lang.String getQuestion () {
		return _question;
	}

	/**
	 * Set the value related to the column: QUESTION
	 * @param _question the QUESTION value
	 */
	public void setQuestion (java.lang.String _question) {
		this._question = _question;
	}


	/**
	 * Return the value associated with the column: FaqSet
	 */
	public java.util.Set getFaqSet () {
		return this._faqSet;
	}

	/**
	 * Set the value related to the column: FaqSet
	 * @param _faqSet the FaqSet value
	 */
	public void setFaqSet (java.util.Set _faqSet) {
		this._faqSet = _faqSet;
	}
	
	public void addToFaqSet (Object obj) {
		if (null == this._faqSet) this._faqSet = new java.util.HashSet();
		this._faqSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseQuestionReponse)) return false;
		else {
			model.base.BaseQuestionReponse mObj = (model.base.BaseQuestionReponse) obj;
			if (null == this.getIdQuestionReponse() || null == mObj.getIdQuestionReponse()) return false;
			else return (this.getIdQuestionReponse().equals(mObj.getIdQuestionReponse()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdQuestionReponse()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdQuestionReponse().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}