package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the abonnement table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="abonnement"
 */
public abstract class BaseAbonnement  implements Serializable {

	public static String PROP_PRIX_ABONNEMENT = "PrixAbonnement";
	public static String PROP_ID_ABONNEMENT = "IdAbonnement";
	public static String PROP_DUREE_ABONNEMENT = "DureeAbonnement";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idAbonnement;

	// fields
	private java.math.BigDecimal _prixAbonnement;
	private java.lang.Long _dureeAbonnement;

	// collections
	private java.util.Set _souscrireSet;


	// constructors
	public BaseAbonnement () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAbonnement (java.lang.Long _idAbonnement) {
		this.setIdAbonnement(_idAbonnement);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAbonnement (
		java.lang.Long _idAbonnement,
		java.math.BigDecimal _prixAbonnement,
		java.lang.Long _dureeAbonnement) {

		this.setIdAbonnement(_idAbonnement);
		this.setPrixAbonnement(_prixAbonnement);
		this.setDureeAbonnement(_dureeAbonnement);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_ABONNEMENT"
     */
	public java.lang.Long getIdAbonnement () {
		return _idAbonnement;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idAbonnement the new ID
	 */
	public void setIdAbonnement (java.lang.Long _idAbonnement) {
		this._idAbonnement = _idAbonnement;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: PRIX_ABONNEMENT
	 */
	public java.math.BigDecimal getPrixAbonnement () {
		return _prixAbonnement;
	}

	/**
	 * Set the value related to the column: PRIX_ABONNEMENT
	 * @param _prixAbonnement the PRIX_ABONNEMENT value
	 */
	public void setPrixAbonnement (java.math.BigDecimal _prixAbonnement) {
		this._prixAbonnement = _prixAbonnement;
	}


	/**
	 * Return the value associated with the column: DUREE_ABONNEMENT
	 */
	public java.lang.Long getDureeAbonnement () {
		return _dureeAbonnement;
	}

	/**
	 * Set the value related to the column: DUREE_ABONNEMENT
	 * @param _dureeAbonnement the DUREE_ABONNEMENT value
	 */
	public void setDureeAbonnement (java.lang.Long _dureeAbonnement) {
		this._dureeAbonnement = _dureeAbonnement;
	}


	/**
	 * Return the value associated with the column: SouscrireSet
	 */
	public java.util.Set getSouscrireSet () {
		return this._souscrireSet;
	}

	/**
	 * Set the value related to the column: SouscrireSet
	 * @param _souscrireSet the SouscrireSet value
	 */
	public void setSouscrireSet (java.util.Set _souscrireSet) {
		this._souscrireSet = _souscrireSet;
	}
	
	public void addToSouscrireSet (Object obj) {
		if (null == this._souscrireSet) this._souscrireSet = new java.util.HashSet();
		this._souscrireSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseAbonnement)) return false;
		else {
			model.base.BaseAbonnement mObj = (model.base.BaseAbonnement) obj;
			if (null == this.getIdAbonnement() || null == mObj.getIdAbonnement()) return false;
			else return (this.getIdAbonnement().equals(mObj.getIdAbonnement()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdAbonnement()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdAbonnement().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}